// AiryBotCode.Frontend/AiryWebApp/src/components/BotList.vue
<script setup lang="ts">
import type { BotSetting } from '../types/botSetting'

defineProps<{
  bots: BotSetting[]
  selectedBotId: string | null
}>()

const emit = defineEmits<{
  (e: 'select', botId: string): void
}>()
</script>

<template>
  <aside class="bot-list">
    <h3 class="bot-list-title">Bots</h3>
    <p v-if="bots.length === 0" class="empty">No bots configured yet.</p>
    <button
      v-for="bot in bots"
      :key="bot.botId"
      type="button"
      class="bot-item"
      :class="{ active: bot.botId === selectedBotId }"
      @click="emit('select', bot.botId)"
    >
      <span class="bot-name">{{ bot.botName || 'Unnamed bot' }}</span>
      <span class="status" :class="bot.enabled ? 'on' : 'off'">
        {{ bot.enabled ? 'Enabled' : 'Disabled' }}
      </span>
    </button>
  </aside>
</template>

<style scoped>
.bot-list {
  background-color: var(--surface);
  border: 1px solid var(--border-color);
  border-radius: 14px;
  padding: 1rem;
  box-shadow: 0 4px 16px var(--shadow);
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.bot-list-title {
  font-size: 1rem;
  color: var(--muted-color);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-bottom: 0.5rem;
}

.empty {
  color: var(--muted-color);
  font-size: 0.9rem;
}

.bot-item {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 0.25rem;
  text-align: left;
  color: var(--text-color);
  border: 1px solid var(--border-color);
  background: var(--surface-2);
  border-radius: 10px;
  padding: 0.75rem 1rem;
  cursor: pointer;
  transition: all 0.15s ease;
}

.bot-item:hover {
  border-color: var(--violet);
  background: var(--surface-hover);
}

.bot-item.active {
  border-color: var(--foxfire);
  background: linear-gradient(90deg, rgba(232, 70, 122, 0.12), rgba(224, 102, 153, 0.08));
}

.bot-name {
  font-weight: 600;
}

.status {
  font-size: 0.75rem;
  font-weight: 500;
}

.status.on {
  color: var(--success-color);
}

.status.off {
  color: var(--muted-color);
}

@media (max-width: 768px) {
  /* Horizontal, swipeable strip of bot chips above the editor. */
  .bot-list {
    flex-direction: row;
    flex-wrap: nowrap;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    gap: 0.5rem;
  }
  .bot-list-title {
    display: none;
  }
  .bot-item {
    flex: 0 0 auto;
    min-width: 9rem;
  }
}
</style>

// AiryBotCode.Frontend/AiryWebpage/src/lib/components/BotList.svelte
<!-- src/lib/components/BotList.svelte -->
<script lang="ts">
    import { createEventDispatcher } from 'svelte';
    import { SearchIcon } from 'svelte-feather-icons';
    import type { BotSetting } from '../types/database';

    export let bots: BotSetting[];
    export let selectedBotId: number | null;

    let searchTerm = '';
    let filteredBots = bots;

    const dispatch = createEventDispatcher();

    $: {
        if (searchTerm) {
            filteredBots = bots.filter(bot =>
                bot.botName.toLowerCase().includes(searchTerm.toLowerCase())
            );
        } else {
            filteredBots = bots;
        }
    }
</script>

<aside class="bot-list-sidebar">
    <div class="header">
        <h2>Bot List</h2>
    </div>
    <div class="search-container">
        <SearchIcon size="20" />
        <input type="text" placeholder="Search bots..." bind:value={searchTerm} />
    </div>
    <nav>
        <ul>
            {#each filteredBots as bot}
                <li>
                    <button 
                        class:active={bot.botId === selectedBotId}
                        on:click={() => dispatch('select', bot.botId)}
                    >
                        <img src={bot.avatarUrl} alt="{bot.botName} avatar" class="avatar" />
                        <span>{bot.botName}</span>
                    </button>
                </li>
            {/each}
        </ul>
    </nav>
</aside>

<style>
    .bot-list-sidebar {
        background-color: #ffffff;
        padding: 1.5rem;
        border-right: 1px solid var(--border-color, #e0e0e0);
        height: 100%;
    }

    .header {
        padding: 0 1rem;
        margin-bottom: 1.5rem;
    }

    h2 {
        font-size: 1.5rem;
    }
    
    .search-container {
        display: flex;
        align-items: center;
        gap: 0.75rem;
        padding: 0 0.75rem;
        margin-bottom: 1.5rem;
        border-radius: 8px;
        border: 1px solid var(--border-color, #e0e0e0);
        background-color: white;
    }
    
    .search-container :global(svg) {
        color: #999;
        flex-shrink: 0;
    }

    input[type="text"] {
        width: 100%;
        border: none;
        outline: none;
        padding: 0.75rem 0;
        font-size: 1rem;
        background-color: transparent;
    }

    ul {
        list-style: none;
        padding: 0;
        margin: 0;
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }

    button {
        display: flex;
        align-items: center;
        gap: 1rem;
        width: 100%;
        padding: 0.75rem 1rem;
        background-color: transparent;
        border: none;
        border-radius: 8px;
        cursor: pointer;
        font-size: 1rem;
        text-align: left;
        color: var(--text-color, #333);
        transition: background-color 0.2s, color 0.2s;
        font-weight: 500;
    }

    button:hover {
        background-color: #e9ecef;
    }

    button.active {
        background-color: #dbeafe; /* A light blue */
        color: #1d4ed8; /* A darker blue for text */
    }

    .avatar {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        object-fit: cover;
    }

    /* On mobile the bot list becomes a horizontal scroll bar above the settings. */
    @media (max-width: 768px) {
        .bot-list-sidebar {
            height: auto;
            border-right: none;
            border-bottom: 1px solid var(--border-color, #e0e0e0);
            padding: 1rem;
        }
        .header { margin-bottom: 1rem; }
        ul {
            flex-direction: row;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
            padding-bottom: 0.25rem;
        }
        li { flex-shrink: 0; }
        button {
            width: auto;
            white-space: nowrap;
            background-color: #f1f3f5;
            min-height: 44px;
        }
        .avatar { width: 28px; height: 28px; }
    }
</style>
