// AiryBotCode.Frontend/AiryWebApp/src/components/CommandModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { CommandConfig } from '../lib/api'

const props = defineProps<{ command: CommandConfig }>()
const emit = defineEmits<{
  (e: 'save', settings: { key: string; value: string }[]): void
  (e: 'close'): void
}>()

// Local editable clone so edits don't mutate the parent until saved.
const draft = ref<CommandConfig>(JSON.parse(JSON.stringify(props.command)))
const saving = ref(false)

function save() {
  saving.value = true
  emit(
    'save',
    draft.value.settings.map((s) => ({ key: s.key, value: s.value })),
  )
}
</script>

<template>
  <div class="overlay" @click.self="emit('close')">
    <div class="modal" role="dialog" aria-modal="true">
      <header class="modal-header">
        <h2>{{ draft.commandName }}</h2>
        <button class="close-btn" aria-label="Close" @click="emit('close')">✕</button>
      </header>

      <div class="modal-body">
        <div v-for="setting in draft.settings" :key="setting.key" class="field">
          <div class="label-row">
            <label :for="`f-${setting.key}`">{{ setting.key }}</label>
            <span class="badge" :class="{ reloadable: setting.isReloadable }">
              {{ setting.isReloadable ? 'auto-applies' : 'needs reload' }}
            </span>
          </div>

          <textarea
            v-if="setting.uiHint === 'textarea' || setting.uiHint === 'json'"
            :id="`f-${setting.key}`"
            v-model="setting.value"
            rows="4"
            :class="{ mono: setting.uiHint === 'json' }"
          ></textarea>
          <input
            v-else-if="setting.uiHint === 'number'"
            :id="`f-${setting.key}`"
            v-model="setting.value"
            type="number"
          />
          <label v-else-if="setting.uiHint === 'boolean'" class="switch">
            <input
              type="checkbox"
              :checked="setting.value === 'true'"
              @change="setting.value = ($event.target as HTMLInputElement).checked ? 'true' : 'false'"
            />
            <span>{{ setting.value === 'true' ? 'Enabled' : 'Disabled' }}</span>
          </label>
          <input v-else :id="`f-${setting.key}`" v-model="setting.value" type="text" />

          <p class="help">{{ setting.description }}</p>
        </div>

        <p v-if="draft.settings.length === 0" class="empty">No configurable settings.</p>
      </div>

      <footer class="modal-footer">
        <button class="cancel-btn" @click="emit('close')">Cancel</button>
        <button class="save-btn" :disabled="saving" @click="save">
          {{ saving ? 'Saving…' : 'Save' }}
        </button>
      </footer>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed;
  inset: 0;
  background: rgba(58, 44, 54, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1.5rem;
  z-index: 100;
}
.modal {
  background: var(--surface-2, #fff);
  border: 1px solid var(--border-color);
  border-radius: 16px;
  width: 100%;
  max-width: 560px;
  max-height: 85vh;
  display: flex;
  flex-direction: column;
  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.22);
}
.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1.25rem 1.5rem 0.75rem;
}
.modal-header h2 {
  margin: 0;
  font-size: 1.25rem;
  color: var(--foxfire-deep);
}
.close-btn {
  background: transparent;
  border: none;
  font-size: 1.1rem;
  cursor: pointer;
  color: var(--muted-color);
  padding: 0.25rem 0.5rem;
  border-radius: 8px;
}
.close-btn:hover { background: var(--surface-hover); }
.modal-body {
  padding: 0.5rem 1.5rem 1rem;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 1.1rem;
}
.field { display: flex; flex-direction: column; gap: 0.4rem; }
.label-row { display: flex; align-items: center; justify-content: space-between; gap: 0.5rem; }
label { font-weight: 600; color: var(--text-color); }
.badge {
  font-size: 0.68rem;
  font-weight: 700;
  padding: 0.12rem 0.5rem;
  border-radius: 999px;
  background: var(--surface-hover);
  color: var(--muted-color);
  white-space: nowrap;
}
.badge.reloadable { background: #e7f6ec; color: #1f9254; }
input[type='text'],
input[type='number'],
textarea {
  width: 100%;
  box-sizing: border-box;
  padding: 0.6rem;
  border: 1px solid var(--input-border, #ecc0cf);
  border-radius: 8px;
  font-size: 16px;
  background: var(--surface-2);
}
textarea { resize: vertical; min-height: 70px; }
textarea.mono { font-family: ui-monospace, Menlo, monospace; font-size: 0.85rem; }
.switch { display: flex; align-items: center; gap: 0.5rem; font-weight: 400; }
.switch input { width: 20px; height: 20px; }
.help { margin: 0; color: var(--muted-color); font-size: 0.8rem; }
.empty { color: var(--muted-color); font-style: italic; }
.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 0.75rem;
  padding: 1rem 1.5rem;
  border-top: 1px solid var(--border-color);
}
.cancel-btn {
  background: var(--surface-2);
  border: 1px solid var(--border-color);
  border-radius: 8px;
  padding: 0.6rem 1.1rem;
  cursor: pointer;
  color: var(--text-color);
}
.save-btn {
  background: var(--foxfire);
  color: #fff;
  border: none;
  border-radius: 8px;
  padding: 0.6rem 1.4rem;
  font-weight: 600;
  cursor: pointer;
}
.save-btn:hover { background: var(--foxfire-deep); }
.save-btn:disabled { opacity: 0.6; cursor: default; }

@media (max-width: 768px) {
  .overlay { padding: 0; align-items: stretch; }
  .modal { max-width: 100%; height: 100dvh; max-height: 100dvh; border-radius: 0; }
  .modal-footer {
    position: sticky;
    bottom: 0;
    background: var(--surface-2, #fff);
    padding-bottom: calc(1rem + env(safe-area-inset-bottom));
  }
  .save-btn, .cancel-btn { min-height: 48px; }
}
</style>

// AiryBotCode.Frontend/AiryWebpage/src/lib/components/CommandModal.svelte
<!-- src/lib/components/CommandModal.svelte -->
<!-- Popup editor for a single command's settings. Edits a local clone and emits
     `save` with the updated config; emits `close` to dismiss. -->
<script lang="ts">
    import { createEventDispatcher } from 'svelte';
    import { SaveIcon, ZapIcon, RefreshCwIcon, XIcon } from 'svelte-feather-icons';
    import type { CommandConfig } from '../types/database';

    export let command: CommandConfig;

    const dispatch = createEventDispatcher();

    let draft: CommandConfig = structuredClone(command);
    let invalidJson: Record<string, boolean> = {};
    let saving = false;

    function validateJson(key: string, value: string) {
        try { JSON.parse(value); invalidJson[key] = false; }
        catch { invalidJson[key] = true; }
        invalidJson = invalidJson;
    }

    async function save() {
        if (Object.values(invalidJson).some(Boolean)) return;
        saving = true;
        dispatch('save', structuredClone(draft));
    }

    function close() {
        dispatch('close');
    }

    function onKeydown(e: KeyboardEvent) {
        if (e.key === 'Escape') close();
    }
</script>

<svelte:window on:keydown={onKeydown} />

<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<div class="overlay" on:click={close}>
    <div class="modal" on:click|stopPropagation role="dialog" aria-modal="true">
        <header class="modal-header">
            <div class="title-block">
                <h2>{draft.displayName}</h2>
                <code class="slug">/{draft.slug}</code>
            </div>
            <button class="close-btn" on:click={close} aria-label="Close"><XIcon size="20" /></button>
        </header>
        <p class="description">{draft.description}</p>

        <form class="modal-body" on:submit|preventDefault={save}>
            {#each draft.settings as setting (setting.key)}
                <div class="form-group">
                    <div class="label-row">
                        <label for="m-{draft.commandName}-{setting.key}">{setting.key}</label>
                        <span
                            class="badge"
                            class:reloadable={setting.isReloadable}
                            title={setting.isReloadable
                                ? 'Applies automatically a few seconds after saving'
                                : 'Applies on the next full bot reload'}
                        >
                            {#if setting.isReloadable}
                                <RefreshCwIcon size="12" /> auto-applies
                            {:else}
                                <ZapIcon size="12" /> needs reload
                            {/if}
                        </span>
                    </div>

                    {#if setting.uiHint === 'textarea'}
                        <textarea id="m-{draft.commandName}-{setting.key}" rows="4" bind:value={setting.value}></textarea>
                    {:else if setting.uiHint === 'json'}
                        <textarea
                            id="m-{draft.commandName}-{setting.key}"
                            class="json" class:invalid={invalidJson[setting.key]} rows="5"
                            bind:value={setting.value}
                            on:input={() => validateJson(setting.key, setting.value)}
                        ></textarea>
                        {#if invalidJson[setting.key]}<span class="json-error">Invalid JSON</span>{/if}
                    {:else if setting.uiHint === 'number'}
                        <input id="m-{draft.commandName}-{setting.key}" type="number" bind:value={setting.value} />
                    {:else if setting.uiHint === 'boolean'}
                        <label class="switch">
                            <input
                                id="m-{draft.commandName}-{setting.key}" type="checkbox"
                                checked={setting.value === 'true'}
                                on:change={(e) => (setting.value = e.currentTarget.checked ? 'true' : 'false')}
                            />
                            <span>{setting.value === 'true' ? 'Enabled' : 'Disabled'}</span>
                        </label>
                    {:else}
                        <input id="m-{draft.commandName}-{setting.key}" type="text" bind:value={setting.value} />
                    {/if}

                    <p class="help">{setting.description}</p>
                </div>
            {/each}

            {#if draft.settings.length === 0}
                <p class="empty">No configurable settings for this command yet.</p>
            {/if}
        </form>

        <footer class="modal-footer">
            <button class="cancel-btn" on:click={close}>Cancel</button>
            <button class="save-btn" on:click={save} disabled={saving}>
                <SaveIcon size="16" /> {saving ? 'Saving…' : 'Save'}
            </button>
        </footer>
    </div>
</div>

<style>
    .overlay {
        position: fixed;
        inset: 0;
        background: rgba(17, 24, 39, 0.55);
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 1.5rem;
        z-index: 100;
    }
    .modal {
        background: var(--card-background, #fff);
        border-radius: 14px;
        width: 100%;
        max-width: 560px;
        max-height: 85vh;
        display: flex;
        flex-direction: column;
        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.25);
    }
    .modal-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 1.25rem 1.5rem 0.5rem;
    }
    .title-block { display: flex; align-items: center; gap: 0.75rem; }
    h2 { margin: 0; font-size: 1.3rem; }
    .slug {
        font-size: 0.8rem; background: #f1f3f5; color: #495057;
        padding: 0.15rem 0.5rem; border-radius: 6px;
    }
    .close-btn {
        background: transparent; border: none; cursor: pointer; color: #6b7280;
        padding: 0.25rem; border-radius: 6px; display: inline-flex;
    }
    .close-btn:hover { background: #f3f4f6; }
    .description { margin: 0; padding: 0 1.5rem 0.5rem; color: #6b7280; font-size: 0.9rem; }
    .modal-body {
        padding: 1rem 1.5rem;
        overflow-y: auto;
        display: flex;
        flex-direction: column;
        gap: 1.25rem;
    }
    .form-group { display: flex; flex-direction: column; gap: 0.4rem; }
    .label-row { display: flex; align-items: center; justify-content: space-between; gap: 0.5rem; }
    label { font-weight: 600; color: #374151; font-size: 0.95rem; }
    .badge {
        display: inline-flex; align-items: center; gap: 0.25rem;
        font-size: 0.7rem; font-weight: 500; padding: 0.15rem 0.45rem;
        border-radius: 999px; background: #fff7ed; color: #c2410c; white-space: nowrap;
    }
    .badge.reloadable { background: #eef2ff; color: #4338ca; }
    input[type='text'], input[type='number'], textarea {
        width: 100%; box-sizing: border-box; padding: 0.55rem;
        border: 1px solid #d1d5db; border-radius: 6px; font-size: 0.9rem; font-family: inherit;
    }
    textarea { resize: vertical; min-height: 70px; }
    textarea.json { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.85rem; }
    textarea.json.invalid { border-color: #dc2626; background: #fef2f2; }
    .json-error { color: #dc2626; font-size: 0.8rem; }
    .switch { display: flex; align-items: center; gap: 0.5rem; font-weight: 400; color: #374151; }
    .switch input { width: 20px; height: 20px; }
    .help { margin: 0; color: #9ca3af; font-size: 0.8rem; }
    .empty { color: #9ca3af; font-style: italic; margin: 0; }
    .modal-footer {
        display: flex; justify-content: flex-end; gap: 0.75rem;
        padding: 1rem 1.5rem; border-top: 1px solid #eef0f3;
    }
    .cancel-btn {
        background: #fff; border: 1px solid #d1d5db; border-radius: 8px;
        padding: 0.6rem 1.1rem; font-size: 0.95rem; cursor: pointer; color: #374151;
    }
    .cancel-btn:hover { background: #f9fafb; }
    .save-btn {
        display: inline-flex; align-items: center; gap: 0.5rem; border: none;
        border-radius: 8px; padding: 0.6rem 1.25rem; font-size: 0.95rem; font-weight: 500;
        cursor: pointer; background: var(--primary-color, #4a90e2); color: #fff;
    }
    .save-btn:hover { filter: brightness(0.95); }
    .save-btn:disabled { opacity: 0.6; cursor: default; }

    /* On phones the modal becomes a full-screen sheet. */
    @media (max-width: 768px) {
        .overlay { padding: 0; align-items: stretch; }
        .modal {
            max-width: 100%;
            width: 100%;
            max-height: 100dvh;
            height: 100dvh;
            border-radius: 0;
        }
        .modal-footer {
            position: sticky;
            bottom: 0;
            background: var(--card-background, #fff);
            /* keep the Save button clear of the iOS home indicator */
            padding-bottom: calc(1rem + env(safe-area-inset-bottom));
        }
        .save-btn, .cancel-btn { min-height: 48px; }
    }
</style>
